server:
  port: 8080
  servlet:
    context-path: /api
management:
  server:
    base-path: /
spring:
  datasource:
    dynamic:
      aop:
        enabled: true
      primary: master
      strict: false
      grace-destroy: true
      datasource:
        master:
          url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://127.0.0.1:5432/llmchat?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8}
          username: ${SPRING_DATASOURCE_USERNAME:postgres}
          password: ${SPRING_DATASOURCE_PASSWORD:llmchat123456}
          driver-class-name: org.postgresql.Driver
      druid:
        initial-size: 4
        min-idle: 4
        max-active: 8
        max-wait: 30000
        time-between-eviction-runs-millis: 60000
        min-evictable-idle-time-millis: 300000
        max-evictable-idle-time-millis: 600000
        validation-query: select 1
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
        keep-alive: true
        pool-prepared-statements: true
        async-init: true
        max-pool-prepared-statement-per-connection-size: 8
  data:
    redis:
      lettuce:
        pool:
          enabled: true
          min-idle: 2
          max-wait: 10s
          time-between-eviction-runs: 60s
          max-active: 16
        shutdown-timeout: 10s
      url: ${SPRING_REDIS_URL:redis://:llmchat123456@127.0.0.1:6379}
      database: 0
      timeout: 15s
      connect-timeout: 10s
      client-type: lettuce
dromara:
  x-file-storage:
    default-platform: minio
    minio:
      - platform: minio
        enable-storage: true
        access-key: ${SPRING_MINIO_ACCESS_KEY:minio}
        secret-key: ${SPRING_MINIO_SECRET_KEY:llmchat123456}
        end-point: ${SPRING_MINIO_END_POINT:http://127.0.0.1:9000}
        bucket-name: llmchat
        domain: ${SPRING_MINIO_DOMAIN_HOST:http://127.0.0.1:9000/llmchat/}
        base-path: datasets/
langchain4j:
  embedding:
    api-key: ${SPRING_EMBEDDING_API_KEY:RgAbHv1w8Zh62GUzIq0ojWMQdaxiut5l3LmJ}
    scheme: ${SPRING_EMBEDDING_SCHEME:http}
    host: ${SPRING_EMBEDDING_HOST:127.0.0.1:58080}
    object-class: Ai_Embeddings